### ISSUE TITLE
text align .right

### ISSUE THREAD

**Issue by abumami** [malcommac/SwiftRichString#4]
Is there anyway to cause this library to have the text align default to .right? This would be very helpful for Hebrew and Arabic.

Thanks

**Comment by malcommac** [comment]
Hi @abumami , since 0.9.5 you will found `.writingDirection` property which allows you to define the direction of the text (`leftToRight`, `rightToLeft` or `natural`).
This is the commit:
https://github.com/malcommac/SwiftRichString/commit/d9b7549919fcdf5f54e8738a1ffd737146b139c9

I'll release it later today.

**Comment by abumami** [comment]
Hey @malcommac, that was fast!
You are a gentleman and a scholar.

I'll try it out and let you know.

Thanks!

**Comment by malcommac** [comment]
You are welcome 👍  Thank you!

**Comment by abumami** [comment]
Hey @malcommac, forgot to ask before...

Is there any way to apply Writing Direction (Right-To-Left) as a document default? This way the direction attribute doesn't have to be added to the styles.

Thanks
