### ISSUE TITLE
What about <p> tag for paragraph separation?

### ISSUE THREAD

**Issue by halonsoluis** [malcommac/SwiftRichString#8]
Hi,
I would like to have a **p** tag instead of **/n** or **br** for paragraph delimitation.
And of course to be able to define a base style for a paragraph that could be changed automatically in favor of other styles selected.
There's a way to set style priority and to successful process this tag?

Right know it just ignore it

**Comment by malcommac** [comment]
Hi @halonsoluis , why a p tag instead of /n?
You can define your own style for each paragraph by defining your own styles:
```
<par1>Bla bla bla</par1>\n
<par2>Again bla bla</par2>
```

Then you'll need to create a two `Style`, one named par1 and the other par2.
Using `MarkupString` class you can read and parse your string, then you can use `render` func to apply your defined styles.
Is this what you would to accomplish?

**Comment by petkrein** [comment]
Hi @malcommac,

why the **<p>** and **<br>** Tag is not working out of the box?
