### ISSUE TITLE
Transform original string through style (TextTransform for Style)

### ISSUE THREAD

**Issue by stefanomondino** [malcommac/SwiftRichString#93]
Sometimes it can be useful to have a `Style` capable of transforming the string itself.
Our current use case scenario is this one: 
- we are in the middle of development and already have a lot of views with labels. Each label has its custom `Style`
- Backend started to send us HTML entities (`&amp;` instead of `&` is the most annoying example).  
- Not being able to display HTML entities should be an issue on the `UILabel` 

Another use case scenario is this #91 

I believe something like this could work: 
```swift
Style {
 $0.color = UIColor.black
 $0.transform = { text in
       text.replacingOccurrences(of: "&amp:", with: "&")
     }
}
```

Or even something more complex like BonMot is doing [here](https://github.com/Rightpoint/BonMot/blob/master/Sources/Transform.swift)

I'll try to put together a PR.

**Comment by stefanomondino** [comment]
Way more difficult than I expected.
Transforming input string is quite easy for simple `Style`, but for `StyleGroup` is REALLY hard.
Having the chance to manipulate the string by changing its length messes up with ranges used to detect tags.

**Comment by malcommac** [comment]
It will be available inside the next release.

### Custom Text Transforms

Sometimes you want to apply custom text transforms to your string; for example you may want to make some text with a given style uppercased with current locale.  
In order to provide custom text transform in `Style` instances just set one or more `TextTransform` to your `Style`'s `.textTransforms` property:

```swift
let allRedAndUppercaseStyle = Style({
	$0.font = UIFont.boldSystemFont(ofSize: 16.0)
	$0.color = UIColor.red
	$0.textTransforms = [
		.uppercaseWithLocale(Locale.current)
	]
})

let text = "test".set(style: allRedAndUppercaseStyle) // will become red and uppercased (TEST)
```

While `TextTransform` is an enum with a predefined set of transform you can also provide your own function which have a `String` as source and another `String` as destination:

```swift
let markdownBold = Style({
	$0.font = UIFont.boldSystemFont(ofSize: 16.0)
	$0.color = UIColor.red
	$0.textTransforms = [
		.custom({
			return "**\($0)**"
		})
	]
})
```

All text transforms are applied in the same ordered you set in `textTransform` property.
