### ISSUE TITLE
Using UILabel with a named image results in a color issue. 

### ISSUE THREAD

**Issue by nkavian** [malcommac/SwiftRichString#98]
**Expected Result**

When using `<img named="SomeImage">` with a UILabel, I expect the image to render exactly as it would in a browser.

**Actual Result**

The image will render as a black&white image but tinted to the UILabel's color. In some cases it will just display the UIImage as solid white or solid black. There is some kind of interaction between the UILabel text color and the UIImage rendering.

**Steps to Reproduce**

- Download the Google Image `https://www.google.com/images/branding/googlelogo/2x/googlelogo_color_92x30dp.png`
- Create a UILabel with a text color of black.
- Use SwiftRichString to add a named image using the Google image.
- Notice the Google letters will all render solid black.
- Change the UILabel color to red and notice the image now renders solid red letters.

**Comment by lucasmpaim** [comment]
Any news about this one?

**Comment by malcommac** [comment]
I've no problem rendering the image in its original form. Be sure to set the "Render As" of your assets image to "Original Image" (or "Default") and not as "Template" in order to avoid this issue.

**Comment by malcommac** [comment]
Due to a bug in UIKit when allocating `NSTextAttachment` it seems ignoring the rendering mode of UIImage instances and apply a template color (the text color of the remaining part of the text).
Now I've introduced a fix which fixes it and render then image correctly when you set the original mode.
Thanks for reporting it. I'll include it into the next update I plan to release in a very few days.

**Comment by malcommac** [comment]
Fixed in 3.6.0
